name: "Tian Lab"
description: "Tian Lab at SUSTech"
baseurl: "https://tianlab.top"
gems: [jekyll-paginate]
paginate: 5
paginate_path: "news/page:num"
excerpt_separator: <!--more-->
exclude: [vendor]
permalink: pretty
highlighter: rouge
markdown: kramdown
kramdown: 
  parse_block_html: true
